// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type HomeDocumentDataSlicesSlice = FeatureSlice | HeroHeadingSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice = FeatureSlice | HeroHeadingSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Category field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | CategoryDocument
  | HomeDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *Feature → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Heading Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.heading_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_text: prismic.KeyTextField;

  /**
   * Paragraph Text field in *Feature → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.paragraph_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_text: prismic.RichTextField;

  /**
   * Main Image field in *Feature → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Main Image Aspect Ratio field in *Feature → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Square (1/1)
   * - **API ID Path**: feature.primary.main_image_ar
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  main_image_ar: prismic.SelectField<
    "Square (1/1)" | "Landscape (3:2)" | "Portrait (2:3)",
    "filled"
  >;

  /**
   * Button 1 Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField;

  /**
   * Button 1 Link field in *Feature → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_1_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_link: prismic.LinkField;

  /**
   * Button 2 Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField;

  /**
   * Button 2 Link field in *Feature → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_link: prismic.LinkField;
}

/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Feature → Primary*
 */
export interface FeatureSliceFeature192Primary {
  /**
   * Eyebrow Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Heading Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.heading_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_text: prismic.KeyTextField;

  /**
   * Paragraph Text field in *Feature → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.paragraph_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_text: prismic.RichTextField;

  /**
   * Main Image field in *Feature → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Main Image Aspect Ratio field in *Feature → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Square (1/1)
   * - **API ID Path**: feature.primary.main_image_ar
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  main_image_ar: prismic.SelectField<
    "Square (1/1)" | "Landscape (3:2)" | "Portrait (2:3)",
    "filled"
  >;

  /**
   * Button 1 Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField;

  /**
   * Button 1 Link field in *Feature → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_1_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_link: prismic.LinkField;

  /**
   * Button 2 Text field in *Feature → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField;

  /**
   * Button 2 Link field in *Feature → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.button_2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_link: prismic.LinkField;
}

/**
 * Feature 192 variation for Feature Slice
 *
 * - **API ID**: `feature192`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSliceFeature192 = prismic.SharedSliceVariation<
  "feature192",
  Simplify<FeatureSliceFeature192Primary>,
  never
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault | FeatureSliceFeature192;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroHeadingSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Main Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.mainImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainImage: prismic.ImageField<never>;

  /**
   * Call to Action 1 Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta1Text: prismic.KeyTextField;

  /**
   * Call to Action 1 Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta1Link: prismic.LinkField;

  /**
   * Call to Action 2 Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta2Text: prismic.KeyTextField;

  /**
   * Call to Action 2 Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta2Link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroHeadingSliceHero5Primary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Main Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.mainImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainImage: prismic.ImageField<never>;

  /**
   * Call to Action 1 Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta1Text: prismic.KeyTextField;

  /**
   * Call to Action 1 Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta1Link: prismic.LinkField;

  /**
   * Call to Action 2 Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta2Text: prismic.KeyTextField;

  /**
   * Call to Action 2 Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta2Link: prismic.LinkField;
}

/**
 * Hero 5 variation for Hero Slice
 *
 * - **API ID**: `hero5`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeadingSliceHero5 = prismic.SharedSliceVariation<
  "hero5",
  Simplify<HeroHeadingSliceHero5Primary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroHeadingSliceVariation =
  | HeroHeadingSliceDefault
  | HeroHeadingSliceHero5;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_heading`
 * - **Description**: HeroHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeadingSlice = prismic.SharedSlice<
  "hero_heading",
  HeroHeadingSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoryDocument,
      CategoryDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceFeature192Primary,
      FeatureSliceVariation,
      FeatureSliceDefault,
      FeatureSliceFeature192,
      HeroHeadingSlice,
      HeroHeadingSliceDefaultPrimary,
      HeroHeadingSliceHero5Primary,
      HeroHeadingSliceVariation,
      HeroHeadingSliceDefault,
      HeroHeadingSliceHero5,
    };
  }
}
