// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = HeroHeadingSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice = HeroHeadingSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | PageDocument | SettingsDocument;

/**
 * Primary content in *HeroHeading → Primary*
 */
export interface HeroHeadingSliceDefaultPrimary {
  /**
   * Heading field in *HeroHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * text field in *HeroHeading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Main Image field in *HeroHeading → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.mainImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainImage: prismic.ImageField<never>;

  /**
   * Call to Action 1 Text field in *HeroHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta1Text: prismic.KeyTextField;

  /**
   * Call to Action 1 Link field in *HeroHeading → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta1Link: prismic.LinkField;

  /**
   * Call to Action 2 Text field in *HeroHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta2Text: prismic.KeyTextField;

  /**
   * Call to Action 2 Link field in *HeroHeading → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta2Link: prismic.LinkField;
}

/**
 * Default variation for HeroHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroHeading → Primary*
 */
export interface HeroHeadingSliceHeroWithVideoPrimary {
  /**
   * Heading field in *HeroHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * text field in *HeroHeading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Main Image field in *HeroHeading → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.mainImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainImage: prismic.ImageField<never>;

  /**
   * Call to Action 1 Text field in *HeroHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta1Text: prismic.KeyTextField;

  /**
   * Call to Action 1 Link field in *HeroHeading → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta1Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta1Link: prismic.LinkField;

  /**
   * Call to Action 2 Text field in *HeroHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta2Text: prismic.KeyTextField;

  /**
   * Call to Action 2 Link field in *HeroHeading → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.cta2Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta2Link: prismic.LinkField;

  /**
   * Video Link field in *HeroHeading → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_heading.primary.videoLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  videoLink: prismic.LinkField;
}

/**
 * Hero - with Video variation for HeroHeading Slice
 *
 * - **API ID**: `heroWithVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeadingSliceHeroWithVideo = prismic.SharedSliceVariation<
  "heroWithVideo",
  Simplify<HeroHeadingSliceHeroWithVideoPrimary>,
  never
>;

/**
 * Slice variation for *HeroHeading*
 */
type HeroHeadingSliceVariation =
  | HeroHeadingSliceDefault
  | HeroHeadingSliceHeroWithVideo;

/**
 * HeroHeading Shared Slice
 *
 * - **API ID**: `hero_heading`
 * - **Description**: HeroHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeadingSlice = prismic.SharedSlice<
  "hero_heading",
  HeroHeadingSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      HeroHeadingSlice,
      HeroHeadingSliceDefaultPrimary,
      HeroHeadingSliceHeroWithVideoPrimary,
      HeroHeadingSliceVariation,
      HeroHeadingSliceDefault,
      HeroHeadingSliceHeroWithVideo,
    };
  }
}
